version: '3.1'
services:
  server:
    image: ethereum/client-go:latest
    container_name: light_srv
    entrypoint:
      - geth
      - --lightserv=100
      - --nousb
      - --syncmode=fast
      - --rpc
      - --rpcapi=les,admin
      - --rpcaddr=0.0.0.0
      - --goerli
    expose:
      - 8545
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
